create table public.orders (
  id bigint generated by default as identity primary key,
  stripe_checkout_session_id text unique not null,
  stripe_payment_intent_id text,
  customer_email text not null,
  customer_name text,
  shipping_address jsonb,
  amount_total integer not null check (amount_total >= 0),
  currency text not null,
  status text not null default 'paid' check (status in ('paid', 'refunded', 'cancelled')),
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_name text not null,
  product_slug text not null,
  unit_amount integer not null check (unit_amount >= 0),
  quantity integer not null check (quantity > 0)
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- RLS stays on so the publishable key cannot read orders. The webhook uses the
-- service role, which still needs table/sequence grants to query through PostgREST.
grant all on table public.orders to service_role;
grant all on table public.order_items to service_role;
grant usage, select on sequence public.orders_id_seq to service_role;
grant usage, select on sequence public.order_items_id_seq to service_role;
