create table public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  region text not null,
  country text not null,
  price_cents integer not null check (price_cents >= 0),
  description text not null,
  ingredients text not null,
  package_size text not null,
  dietary text[] not null default '{}',
  tone text not null,
  accent text not null,
  shape text not null check (shape in ('round', 'crescent', 'folded', 'pleated')),
  image_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
grant usage on schema public to anon;
grant select on table public.products to anon;
create policy "Anyone can read active products" on public.products for select to anon using (is_active = true);

insert into public.products (slug, name, region, country, price_cents, description, ingredients, package_size, dietary, tone, accent, shape, sort_order) values
  ('soup-dumplings', 'Soup Dumplings', 'Jiangnan', 'China', 1800, 'Tender wrappers filled with slow-simmered pork and a deeply savory broth.', 'Pork, ginger, scallion, sesame', '12 dumplings · serves 2', array['Contains pork'], '#e9d6bb', '#b97948', 'round', 1),
  ('vegetable-momo', 'Vegetable Momo', 'Himalayas', 'Nepal & Tibet', 1600, 'Pillowy steamed dumplings brightened with cabbage, carrot, ginger, and toasted spices.', 'Cabbage, carrot, ginger, garlic', '14 dumplings · serves 2', array['Vegan'], '#c9d7cb', '#688266', 'pleated', 2),
  ('wild-mushroom-pelmeni', 'Wild Mushroom Pelmeni', 'Eastern Europe', 'Ukraine & Russia', 1700, 'Little hand-folded parcels of earthy mushroom, potato, and caramelized onion.', 'Mushroom, potato, onion, dill', '16 dumplings · serves 2–3', array['Vegetarian'], '#c5b1a0', '#725848', 'folded', 3),
  ('chicken-gyoza', 'Chicken Gyoza', 'Japan', 'Japan', 1600, 'Crisp-bottomed dumplings with chicken, cabbage, chive, and a touch of white pepper.', 'Chicken, cabbage, chive, ginger', '12 dumplings · serves 2', array['Contains chicken'], '#d2c9b7', '#92724f', 'crescent', 4);

insert into storage.buckets (id, name, public) values ('product-images', 'product-images', true) on conflict (id) do nothing;
create policy "Public can view product images" on storage.objects for select to public using (bucket_id = 'product-images');
